import { getCurrentSession } from "@/lib/cache/current-session";
import { Metadata } from "next";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Outfit - auth",
  description: "Generated by create next app",
};

export default async function AuthLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const { user } = await getCurrentSession();
  if (user) redirect("/");

  return (
    <>
      <div className="min-h-screen grid place-items-center">
        <div className="w-screen max-w-md">{children}</div>
      </div>
    </>
  );
}
