import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Outfit - auth",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <>
      <div className="min-h-screen grid place-items-center">
        <div className="w-screen max-w-md">{children}</div>
      </div>
    </>
  );
}
