import type { Metadata } from "next";
import "./globals.css";
import "@fontsource-variable/outfit";

export const metadata: Metadata = {
  title: "Outfit",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body>{children}</body>
    </html>
  );
}
